=== Pawel-12/solvd_sql_tasks/src/main/resources/bank.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="CardType">
        <xs:all>
            <xs:element name="account" type="AccountType"/>
            <xs:element name="cardtype" type="CardTypeClass"/>
            <xs:element name="cardNumber" type="xs:string"/>
            <xs:element name="isBlocked" type="xs:boolean"/>
            <xs:element name="validUntil" type="xs:date"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="CardsType">
        <xs:sequence>
            <xs:element name="card" type="CardType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CardTypeClass">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="limit" type="xs:long"/>
            <xs:element name="multicurrency" type="xs:boolean"/>
            <xs:element name="exchangeFeeRate" type="xs:float"/>
            <xs:element name="creditFeeRate" type="xs:float"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="CardTypesClass">
        <xs:sequence>
            <xs:element name="cardtype" type="CardTypeClass"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AccountType">
        <xs:all>
            <xs:element name="client" type="ClientType"/>
            <xs:element name="balance" type="xs:long"/>
            <xs:element name="currency" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="AccountsType">
        <xs:sequence>
            <xs:element name="account" type="AccountType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ClientType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
            <xs:element name="monthlyIncome" type="xs:int"/>
            <xs:element name="totalDebt" type="xs:int"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="ClientsType">
        <xs:sequence>
            <xs:element name="client" type="ClientType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConsultantType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="phone" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="ConsultantsType">
        <xs:sequence>
            <xs:element name="consultant" type="ConsultantType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BankType">
        <xs:sequence>
            <xs:element name="consultants" type="ConsultantsType"/>
            <xs:element name="clients" type="ClientsType"/>
            <xs:element name="accounts" type="AccountsType"/>
            <xs:element name="cardtypes" type="CardTypesClass"/>
            <xs:element name="cards" type="CardsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="bank" type="BankType"/>

</xs:schema>

=== Pawel-12/solvd_sql_tasks/src/main/resources/bank.xml
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="bank.xsd">
    <consultants>
        <consultant id="1">
            <name>Mike</name>
            <surname>Jacobs</surname>
            <phone>123456789</phone>
        </consultant>
    </consultants>

    <clients>
        <client id="1">
            <name>Bob</name>
            <surname>Smith</surname>
            <phone>123456123</phone>
            <monthlyIncome>1000</monthlyIncome>
            <totalDebt>30000</totalDebt>
        </client>
    </clients>

    <accounts>
        <account id="1">
            <client id="1">
                <name>Bob</name>
                <surname>Smith</surname>
                <phone>123456123</phone>
                <monthlyIncome>1000</monthlyIncome>
                <totalDebt>30000</totalDebt>
            </client>
            <balance>5000</balance>
            <currency>USD</currency>
        </account>
    </accounts>

    <cardtypes>
        <cardtype id="1">
            <name>Credit card</name>
            <limit>40000</limit>
            <multicurrency>true</multicurrency>
            <exchangeFeeRate>0.045</exchangeFeeRate>
            <creditFeeRate>0.12</creditFeeRate>
        </cardtype>
    </cardtypes>

    <cards>
        <card id="1">
            <account id="1">
                <client id="1">
                    <name>Bob</name>
                    <surname>Smith</surname>
                    <phone>123456123</phone>
                    <monthlyIncome>1000</monthlyIncome>
                    <totalDebt>30000</totalDebt>
                </client>
                <balance>5000</balance>
                <currency>USD</currency>
            </account>
            <cardtype id="1">
                <name>Credit card</name>
                <limit>40000</limit>
                <multicurrency>true</multicurrency>
                <exchangeFeeRate>0.045</exchangeFeeRate>
                <creditFeeRate>0.12</creditFeeRate>
            </cardtype>
            <cardNumber>1234567812345678</cardNumber>
            <isBlocked>false</isBlocked>
            <validUntil>2024-08-12</validUntil>
        </card>
    </cards>
</bank>
